name: Documentation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - 'foundation/**/README.md'
      - 'implementations/**/README.md'
      - '**/docs/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'foundation/**/README.md'
      - 'implementations/**/README.md'
      - '**/docs/**'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install documentation dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-minify-plugin mkdocstrings mkdocstrings-python
      - name: Build documentation
        run: |
          mkdocs build
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: site/
          retention-days: 7

  publish-docs:
    needs: build-docs
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install documentation dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-minify-plugin mkdocstrings mkdocstrings-python
      - name: Deploy documentation
        run: |
          mkdocs gh-deploy --force

  api-reference:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install documentation dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints
          pip install -e .
      - name: Generate API reference documentation
        run: |
          cd docs/api-reference
          sphinx-build -b html . _build/html
      - name: Upload API documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: api-documentation
          path: docs/api-reference/_build/html/
          retention-days: 7